### ISSUE TITLE
"Error 401 Unauthorized" when I think I should be authorized

### ISSUE THREAD

**Issue by rossos** [Adarnof/adarnauth-esi#6]
I have a logged-in Django user with a valid token that I can see in the DB table "esi_token" (it happens to have pk=6) with appropriate associated scopes, including "esi-markets.structure_markets.v1". Specifying an appropriate value for ``locationid`` first and then running the following in a shell gives me a 401 Unauthorized error when I would expect it to complete without issue:

```
>>> token = Token.objects.get(pk=6)
>>> client = token.get_esi_client()
 ...\bravado_core\spec.py:146: Warning: config also_return_response is not a recognized config key
  category=Warning,
>>> future = client.Market.get_markets_structures_structure_id(structure_id=locationid)
>>> result = future.result()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "...\esi\clients.py", line 86, in result
    return super(CachingHttpFuture, self).result(**kwargs)
  File "...\bravado\http_future.py", line 62, in wrapper

    return func(self, *args, **kwargs)
  File "...\bravado\http_future.py", line 121, in result

    self.response_callbacks)
  File "...\bravado\http_future.py", line 172, in unmarshal_response
    raise_on_expected(incoming_response)
  File "...\bravado\http_future.py", line 232, in raise_on_expected
    swagger_result=http_response.swagger_result)
bravado.exception.HTTPUnauthorized: 401 Unauthorized: {'error': 'Authorization not provided'}
```

I'm wondering if possibly the token information isn't being correctly propagated into the request header? Although this is based on a shaky understanding of how bravado passes this information around. At least, executing the following in the same shell doesn't show me any authorization/bearer strings that I would expect with a token authenticator:

```>>> import http.client
>>> http.client.HTTPConnection.debuglevel = 5
>>> result = future.result()
DEBUG:urllib3.connectionpool:Resetting dropped connection: esi.evetech.net
send: b'GET /latest/markets/structures/<locationid>/ HTTP/1.1
Host: esi.evetech.net
Accept: */*
User-Agent: python-requests/2.18.4
Connection: keep-alive
Accept-Encoding: gzip, deflate

'
reply: 'HTTP/1.1 401 Unauthorized
'
DEBUG:urllib3.connectionpool:https://esi.evetech.net:443 "GET /latest/markets/structures/<locationid>/ HTTP/1.1" 401 39
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  <..same as before..>
```

**Comment by Adarnof** [comment]
CCP has recently shifted from `esi.tech.ccp.is` to `esi.evetech.net`. The `TokenAuthenticator` checks to match the hostname before applying the authorization header - if you're pulling a swaggerspec straight from CCP it'll say the host is `esi.evetech.net` but the default setting in the esi app is `esi.tech.ccp.is` so the token isn't applied. This behaviour can be changed by overriding the [`ESI_API_URL` setting](https://github.com/Adarnof/adarnauth-esi/blob/master/esi/app_settings.py#L26) or manually changing the host defined in the swagger spec.

**Comment by rossos** [comment]
This makes perfect sense, but it would have taken unknown amounts of frustration for me to figure it out myself. Thanks!
